default_stages:
- commit
repos:
- repo: local
  hooks:
  - id: make-check-commit
    name: Check commit message
    stages: [commit-msg]
    entry: make check-commit
    language: system
    require_serial: true
    always_run: true
    pass_filenames: false
  - id: make-docs
    name: Check docs build
    entry: make docs
    language: system
    pass_filenames: false
    types_or: [markdown, sql, yaml]
  - id: make-lint
    name: Run code styling checks
    entry: make lint
    language: system
    types: [sql]
    pass_filenames: false
  - id: make-test
    name: Run unit tests
    entry: make test DIFF=true
    language: system
    types_or: [sql, yaml]
    pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-json
  - id: check-yaml
    files: ^(?!.gitlab).*\.ya?ml$
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ["--fix", "lf"]
  - id: no-commit-to-branch
    args: ["--branch", "", "--pattern", '^(?!(?:master$|untracked(?:-[-\w]+)?$|[A-Z]{2,}-\d+(?:-[-\w]+)?)$).*$']
  - id: trailing-whitespace
