version: '3.7'

services:
  django_api:
    build:
      context: ../../../Init
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=$ALLOWED_HOSTS
      - SECRET_KEY=$SECRET_KEY
  #    env_file:
  #      - .env
